== Who Am I ?

I am developer :) , yes I am still a developer and will be developer for ever! 

I am currently Red Hat’s Director of Developer Experience, most part of my career was with services industry helping various customers build Java based solutions. 

I am the creator of vertx-maven-plugin(https://vmp.fabric8.io) and he has been an active contributor to OpenSource projects like OpenWhisk, Eclipse Che, fabric8 etc., Apart from being an OpenSource developer and contributor I love sharing my experience on building and deploying Cloud Native Java Applications on Kubernetes/OpenShift.

As Red Hat’s Director of Developer Experience I do active evangelism on Spring Boot, Kubernetes/OpenShift, Serverless(OpenWhisk), Istio and Serverless technologies like OpenWhisk by sharing his knowledge on how to build better Cloud Native Applications using these technologies.

If you are seeing this page then I am sure you are looking for Spring Boot on OpenShift resources, how-tos, demos etc., 

I will not disappoint you in this page I have index all my work related Spring Boot on Kubernetes/OpenShift like blogs, videos, demos, tools etc., I will be updating this page as I add new content.

**Good Luck!** and I hope this will be helpful.

If you have any comments, queries or feedback please feel freesh share them via:

icon:twitter[] https://twitter.com/kamesh_sampath[@kamesh_sampath]| icon:github[] https://github.com/kameshsampath[kameshsampath] | icon:envelope[] kamesh.sampath@hotmail.com | icon:linkedin[] https://www.linkedin.com/in/kameshsampath/[kameshsampath] 

